[package]
name = "rmatrix"
version = "0.1.0"
authors = ["bbdare"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = "0.11.1"
rand = "0.7.2"
num_enum = "0.4.1"
ctrlc = "3.1.3"
